//
//  ChatMessage + ProcessedImage.swift
//  AnacacuyaBot
//
//  Created by Ky on 2026-05-19.
//

import AsyncAlgorithms
import Foundation



extension ChatMessage {
    
    /// A message sent in a chat, processed to be seen by the bot
    struct ProcessedImage {
        
        /// The raw data of the image from Telegram
        let rawData: Data
        
        /// The description of the image as generated by our ML vision model
        let visionModelDescription: String
    }
}



extension ChatMessage.ProcessedImage {
    
    /// Runs the given vision model in the given Ollama instance to describe the given image
    ///
    /// - Parameters:
    ///   - rawData:     The image, as raw bytes
    ///   - visionModel: The vision model which will describe the image
    ///   - ollama:      The Ollama instance which will run the vision mdoel
    init(processing rawData: Data, using visionModel: OllamaModel, in ollama: Ollama) async throws {
        self.init(
            rawData: rawData,
            visionModelDescription: try await ollama.describe(image: rawData, using: visionModel),
        )
    }
}



extension Data {
    /// Runs the given vision model in the given Ollama instance to describe this image (assuming this `Data` represents an image)
    ///
    /// - Parameters:
    ///   - visionModel: The vision model which will describe the image
    ///   - ollama:      The Ollama instance which will run the vision mdoel
    func processedImage(using visionModel: OllamaModel, in ollama: Ollama) async throws -> ChatMessage.ProcessedImage {
        try await .init(processing: self, using: visionModel, in: ollama)
    }
}



extension [Data] {
    /// Runs the given vision model in the given Ollama instance to describe these image (assuming these `Data` represent an image)
    ///
    /// - Parameters:
    ///   - visionModel: The vision model which will describe the image
    ///   - ollama:      The Ollama instance which will run the vision mdoel
    func processedImages(using visionModel: OllamaModel, in ollama: Ollama) async throws -> [ChatMessage.ProcessedImage] {
        try await self
            .async
            .map {
                try await $0.processedImage(using: visionModel, in: ollama)
            }
            .collect()
    }
}
